# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 23:33
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(default='', max_length=80)),
                ('rozloha', models.PositiveIntegerField(default=0)),
                ('pouzivany', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cyklus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spravaPoli.Cast')),
            ],
        ),
        migrations.CreateModel(
            name='Plodina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Pozemok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(default='', max_length=80)),
                ('rozloha', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vysadba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumVysadby', models.DateField(default=datetime.date(2018, 3, 27), verbose_name='Datum vysadby')),
                ('casVysadby', models.TimeField(verbose_name=datetime.time(0, 0))),
                ('naklady', models.PositiveIntegerField(default=0, verbose_name='Naklady')),
                ('vysadeneMnozstvo', models.PositiveIntegerField(default=0, verbose_name='Vysadene mnozstvo (g)')),
                ('cyklus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spravaPoli.Cyklus')),
            ],
        ),
        migrations.CreateModel(
            name='Zber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datumZberu', models.DateField(default=datetime.date(2018, 3, 27), verbose_name='Dátum zberu')),
                ('casZberu', models.TimeField(verbose_name=datetime.time(0, 0))),
                ('uroda', models.PositiveIntegerField(default=0, verbose_name='Úroda')),
                ('zisk', models.PositiveIntegerField(default=0, verbose_name='Zisk (eur)')),
                ('cyklus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spravaPoli.Cyklus')),
            ],
        ),
        migrations.AddField(
            model_name='cyklus',
            name='plodina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spravaPoli.Plodina'),
        ),
        migrations.AddField(
            model_name='cast',
            name='pozemok',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spravaPoli.Pozemok'),
        ),
    ]
