# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spravaPoli', '0002_auto_20180327_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyklus',
            name='vysadba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spravaPoli.Vysadba'),
        ),
        migrations.AlterField(
            model_name='cyklus',
            name='zber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spravaPoli.Zber'),
        ),
    ]
